### ISSUE TITLE
links to wrong docs

### ISSUE THREAD

**Issue by thezoggy** [jaraco/jaraco.context#10]
https://github.com/jaraco/jaraco.context/blob/main/docs/conf.py#L43C27-L43C74

should be
https://jaracocontext.readthedocs.io/en/latest/

**Comment by jaraco** [comment]
The referenced link is for mentions of `jaraco.functools` in the docs. I don't see any references to jaraco.functools in the code, so probably that intersphinx mapping isn't needed, but it shouldn't cause any harm. What led you to believe this link was wrong?

**Comment by thezoggy** [comment]
cause i went to look at the changelog and couldnt as it took me to a different tool

**Comment by jaraco** [comment]
I see. Well, when I open the project here, I see NEWS.rst file with the plaintext changelog. In the readme, I see a badge with a link to the docs and including the [rendered changelog](https://jaracocontext.readthedocs.io/en/latest/history.html). I know it's a little clunky that the docs aren't more prominently linked. That's being tracked in jaraco/skeleton#52.

I hope that helps.
