### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by bswck** [jaraco/jaraco.context#2]
jaraco/skeleton#98

**Comment by jaraco** [comment]
This project now has quite a few type hints and declares itself as typed, but I welcome even more.

**Comment by jaraco** [comment]
Gemini has [some ideas for improvement](https://g.co/gemini/share/453f28c030ab).

**Comment by bswck** [comment]
@jaraco The type hints introduced e051242 are based off on deprecated type aliases. Tracking in #11.

**Comment by jaraco** [comment]
Thanks! I knew it was a risk. Thanks for any contribution you can provide.
